CarWorkshop.MVC/Models/About.cs
namespace CarWorkshop.MVC.Models;

public class About
{
    public string? Tittle { get; set; }

    public string? Description { get; set; }

    public List<string> Tags { get; set; } = new();
}

CarWorkshop.MVC/Models/ErrorViewModel.cs
namespace CarWorkshop.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CarWorkshop.MVC/Models/Notification.cs
namespace CarWorkshop.MVC.Models;

public class Notification
{
    public string Type { get; set; }
    public string Message { get; set; }

    public Notification(string type, string message)
    {
        Type = type;
        Message = message;
    }
}

CarWorkshop.MVC/Controllers/CarWorkshopController.cs
using AutoMapper;
using CarWorkshop.Application.CarWorkshop.Commands;
using CarWorkshop.Application.CarWorkshop.Queries;
using CarWorkshop.Application.CarWorkshopService.Commands;
using CarWorkshop.Application.CarWorkshopService.Queries;
using CarWorkshop.MVC.Extensions;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace CarWorkshop.MVC.Controllers;

public class CarWorkshopController : Controller
{
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;
    
    public CarWorkshopController(IMediator mediator, IMapper mapper)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var carWorkshops = await _mediator.Send(new GetAllCarWorkshopsQuery());
        return View(carWorkshops);
    }

    [Authorize(Roles = "Admin, User")]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "Admin, User")]
    public async Task<IActionResult> Create(CreateCarWorkshopCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);

        this.SetNotification("success", $"Created carworkshop: {command.Name}");

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/CarWorkshopService")]
    public async Task<IActionResult> CreateCarWorkshopService(CreateCarWorkshopServiceCommand command)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        await _mediator.Send(command);

        return Ok();
    }

    [HttpGet]
    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/{encodedName}/CarWorkshopService")]
    public async Task<IActionResult> CreateCarWorkshopService(string encodedName)
    {
        var data = await _mediator.Send(new GetCarWorkshopServicesQuery(encodedName));
        return Ok(data);
    }

    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/{encodedName}/Delete")]
    public async Task<IActionResult> Delete(string encodedName)
    {
        var dto = await _mediator.Send(new GetCarWorkshopByEncodedNameQuery(encodedName));

        if (!dto.IsEditable)
            return RedirectToAction("NoAccess", "Home");

        await _mediator.Send(new DeleteCarWorkshopCommand(encodedName));

        this.SetNotification("info", $"Deleted carworkshop: {encodedName}");

        return RedirectToAction(nameof(Index));
    }

    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/{encodedName}/Details")]
    public async Task<ActionResult> Details(string encodedName)
    {
        var dto = await _mediator.Send(new GetCarWorkshopByEncodedNameQuery(encodedName));
        return View(dto);
    }

    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/{encodedName}/Edit")]
    public async Task<ActionResult> Edit(string encodedName)
    {
        var dto = await _mediator.Send(new GetCarWorkshopByEncodedNameQuery(encodedName));

        if (!dto.IsEditable)
            return RedirectToAction("NoAccess", "Home");

        var command = _mapper.Map<UpdateCarWorkshopCommand>(dto);

        return View(command);
    }

    [HttpPost]
    [Authorize(Roles = "Admin, User")]
    [Route("CarWorkshop/{encodedName}/Edit")]
    public async Task<IActionResult> Edit(UpdateCarWorkshopCommand command)
    {
        if (!ModelState.IsValid)
        {
            return View(command);
        }

        await _mediator.Send(command);

        this.SetNotification("info", $"Edited carworkshop: {command.Name}");

        return RedirectToAction(nameof(Index));
    }
}

CarWorkshop.MVC/Controllers/HomeController.cs
using CarWorkshop.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarWorkshop.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult NoAccess()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CarWorkshop.MVC/Views/CarWorkshop/Create.cshtml
@using CarWorkshop.Application.CarWorkshop.Commands;

@model CreateCarWorkshopCommand;

@{
    ViewData["Title"] = "Add company";
}

<h1>@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form action="/CarWorkshop/Create" method="post">
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description">
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="PhoneNumber">Phone Number</label>
                <input class="form-control" type="text" asp-for="PhoneNumber">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="Street">Street</label>
                <input class="form-control" type="text" asp-for="Street">
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="City">City</label>
                <input class="form-control" type="text" asp-for="City">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="PostalCode">Postal code</label>
                <input class="form-control" type="text" asp-for="PostalCode">
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarWorkshop.MVC/Views/CarWorkshop/Details.cshtml
@model CarWorkshop.Application.CarWorkshop.CarWorkshopDto;

@{
    ViewData["Title"] = $"{@Model.Name} Details";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
</div>

<h3>Services: </h3>
<div id="services" class="row" data-encoded-name=@Model.EncodedName>

</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Back to list</a>
    @if (@Model.IsEditable)
    {
        <a class="btn btn-primary" asp-controller="CarWorkshop" asp-action="Edit" asp-route-encodedName=@Model.EncodedName>Edit</a>
    }
</div>

@section Scripts{
    <script src="~/js/CarWorkshop/Edit.js"></script>
}

CarWorkshop.MVC/Views/CarWorkshop/Edit.cshtml
@using CarWorkshop.Application.CarWorkshop.Commands;
@using CarWorkshop.Application.CarWorkshopService.Commands;

@model UpdateCarWorkshopCommand;

@{
    ViewData["Title"] = $"Edit {@Model.Name}";
    var carWorkshopServiceCommand = new CreateCarWorkshopServiceCommand() 
        {CarWorkshopEncodedName = Model.EncodedName != null ? Model.EncodedName : ""};
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @Html.HiddenFor(model => model.Name)
            @Html.HiddenFor(model => model.EncodedName)
            
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description">
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="PhoneNumber">Phone Number</label>
                <input class="form-control" type="text" asp-for="PhoneNumber">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="Street">Street</label>
                <input class="form-control" type="text" asp-for="Street">
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="City">City</label>
                <input class="form-control" type="text" asp-for="City">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="PostalCode">Postal code</label>
                <input class="form-control" type="text" asp-for="PostalCode">
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <input type="submit" value="Edit" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

<h3>Services: </h3>
<div id="services" class="row" data-encoded-name=@Model.EncodedName>

</div>

<div class="m-3">
    <partial name="_CreateCarWorkshopService" model=carWorkshopServiceCommand/>
    <a asp-action="Index" class="btn btn-secondary">Back to list</a>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/CarWorkshop/Edit.js"></script>
}

CarWorkshop.MVC/Views/CarWorkshop/Index.cshtml
@using CarWorkshop.Application.CarWorkshop;

@model IEnumerable<CarWorkshopDto>

@{
    ViewData["Title"] = "Workshops list";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Create new</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="card m-3" style="width: 18rem">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@item.PhoneNumber</h6>
                <p class="card-text">@item.Description</p>
                <a class="btn btn-primary" asp-controller="CarWorkshop" asp-action="Details" asp-route-encodedName=@item.EncodedName>Details</a>
                @if (item.IsEditable)
                {
                    <a class="btn btn-outline-secondary btn-sm" asp-controller="CarWorkshop" asp-action="Edit" asp-route-encodedName=@item.EncodedName>Edit</a>
                    <a class="btn btn-danger btn-sm" asp-controller="CarWorkshop" asp-action="Delete" asp-route-encodedName=@item.EncodedName>Delete</a>
                }
            </div>
        </div>
    }
</div>

CarWorkshop.MVC/Views/CarWorkshop/_CreateCarWorkshopService.cshtml
@model CarWorkshop.Application.CarWorkshopService.Commands.CreateCarWorkshopServiceCommand

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createCarWorkshopServiceModal">
    Add carworkshop service
</button>

<!-- Modal -->
<div class="modal fade" id="createCarWorkshopServiceModal" tabindex="-1" aria-labelledby="createCarWorkshopServiceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action="CreateCarWorkshopService">

                <div class="modal-header">
                    <h5 class="modal-title" id="createCarWorkshopServiceModalLabel">Create new carworkshop service</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input asp-for="CarWorkshopEncodedName" class="form-control" type="hidden" />

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cost" class="control-label"></label>
                        <input asp-for="Cost" class="form-control" />
                        <span asp-validation-for="Cost" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" value="Create" class="btn btn-primary">
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarWorkshop.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Multiplatfom ASP.NET simple CRUD demo to manage car workshops.</p>
</div>

CarWorkshop.MVC/Views/Home/NoAccess.cshtml
@{
    ViewData["Title"] = "Permissions denied";
}
<h1>@ViewData["Title"]</h1>

<div class="alert alert-danger" style="display: inline-block;" role="alert">
    You don't have permissions to access that resource!
</div>

CarWorkshop.MVC/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;

@{
    var action = ViewContext.RouteData.Values["action"]?.ToString();
    var controller = ViewContext.RouteData.Values["controller"]?.ToString();
    var notification = TempData["Notification"] != null ? 
        JsonConvert.DeserializeObject<Notification>(TempData["Notification"]!.ToString()!)! : null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWorkshop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarWorkshop.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car Workshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller == "Home" && action == "Index" ? "active" : "")" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller == "CarWorkshop" && action == "Index" ? "active" : "")" asp-controller="CarWorkshop" asp-action="Index">Workshops</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Car Workshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @if (notification != null)
    {
        <script>
            toastr["@notification.Type"]("@notification.Message")
        </script>
    }

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>